[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "full"

cursor:
  style:
    shape: Beam
    blinking: On

font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  size: 13.0

window:
  padding:
    x: 6
    y: 6
  opacity: 0.95




